contributte/nusoap

src/nusoap.php

Although this repo is only a PHP 7 compatible fork and the official nusoap seems not to be maintained anymore I've got this small snippet to support namespaces in nusoap methods like register().
Credits for this snippets belongs to the stackoverflow user in this thread: http://stackoverflow.com/questions/30669749/registering-namespaced-php-class-methods-with-nusoap#answer-43096118
I've made this change in the composer installed core file and if this PR might be merged i don't have to bother that my change got overwritten by any update. 
Anyway, thanks for porting to php7 :)

Update invokeMethod to support namespaces

---

src/nusoap.php

From: [NuSoap version 0.9.5 Attempt to modify property of non-object in nusoap.php](http://www.noaheltzroth.com/nusoap-version-0-9-5-attempt-to-modify-property-of-non-object-in-nusoap-php/):
> I am working with NuSoap and a particular WSDL file was causing the following error for me:
>
> PHP Warning: Attempts to modify property of non-object in lib/nusoap.php on line 4694.
> To fix this problem I modified line 4694 in nusoap.php from:
>
>$this->schemas[$ns]->imports[$ns2][$ii]['loaded'] = true;
>
>To this:
>
> $this->schemas[$ns][$ns2]->imports[$ns2][$ii]['loaded'] = true;
>
> And that fixed the problem.  I found the solution in the NuSoap forums, but I though I would share the information as a post in the hopes it make it easier for someone else to find, and my line number was different …

Fix "Warning: attempt to modify property of non-object"

---

src/nusoap.php

Set default prefix and namespace to prevent error Undefined variable $prefix and $namespace if (preg_match('/:/', $name)) return 0 or FALSE

Set default prefix and namespace

---

src/nusoap.php

Hi, I needed to set an empty Soap Action registering a method and noticed that when the parameter is an empty string gets overwritten due to a false (default value) comparison.

Fix false comparison to allow empty SoapAction

---

src/nusoap.php

Also of note:
- suppressed some potential php errors
- tested in php 7.3

Allow configuration of http content-type to allow content-types like 'application/soap+xml'

---

src/nusoap.php

The previous notation was still allowing some warnings, and depending on your configuration in E_STRICT throws exceptions.
This will prevent warnings and exceptions when using php 7.4

7.4 compatibility

---

samples/wsdlclient12.php
samples/wsdlclient14.php
samples/wsdlclient4.php
src/nusoap.php

Fixes some vulnerabilities pointed out by Veracode.

Fix CWE errors

---

src/nusoap.php

Although the text specification of SOAP 1.1 only names the children
of the Fault element, the XSD at http://schemas.xmlsoap.org/soap/envelope/
defines them as a "sequence", implying a fixed order (faultcode,
faultstring, faultactor, detail).
Some clients, particularly using .NET, are reported to have issues
parsing the response if the elements don't match that order.
This was reported on Sourceforge as long ago as 2011:
https://sourceforge.net/p/nusoap/discussion/193579/thread/9a5aff36/

Re-arrange child elements of Fault XML to match SOAP 1.1 XSD

---

.travis.yml
README.md
composer.json
src/nusoap.php

* Fixes a deprecation on PHP 8
* Replaces abandoned composer dependency for testing
* Update Readme/config for PHP 8

Add support for PHP 8

---

.travis.yml
composer.json
src/nusoap.php

PHP 8.1 deprecates strftime. Nusoap uses that. This pull request removes the use of strftime, and replaces it with what should be its functional equivalent.

Make work with PHP 8.1 (strftime deprecation)

---

src/nusoap.php

On PHP 8.2 utf8_decode is going to be deprecated, maybe we can start changing that
https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated
https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated#utf8_decode-mbstring

`mb_convert_encoding` support

---

src/nusoap.php

In function serialize_return, $this->methodreturn can be an array, resulting in "PHP Warning: get_class() expects parameter 1 to be object, array given" Above code change fixes this by checking for object. However, without knowing the complete flow, I am unsure if there is an underlying issue which assigns incorrect type to $this->methodreturn.

$this->methodreturn can be array

---

src/nusoap.php

Replaces hardcoded use of ISO-8859-1 charset in wsdl with the configured charset from soap_defencoding and thus fixes the error "Charset from HTTP Content-Type 'UTF-8' does not match encoding from XML declaration 'ISO-8859-1'" for clients consuming the wsdl, when the server defaults to UTF-8.

Enable option to use UTF-8 encoding in wsdl.

---

src/nusoap.php

Adding two "skippable" headers with title casing.
I ran into this problem when using Apache as a forward proxy. It fixes the issue when trying to parse the XML but not all of the HTTP headers have been stripped, and you end up with this error:
```
wsdl: XML error parsing WSDL from https://soap.acme.org?WSDL on line 1: Not well-formed (invalid token)
```

Add skippable proxy header

---

src/nusoap.php

Solve problem with current http://schemas.xmlsoap.org/wsdl/ to https redirect, which is done by HTTP 307.

set HTTP 307 Temporary Redirect as known HTTP status code

---

src/nusoap.php

- solved warning of undefined array key $attachment['boundaryStr']
- solved deprecated passing null to stripos (thanks to undefined key of array)
- if key is undefined return false - same return value as stripos do not find boundary string in XML string

fix - undefined array key boundaryStr and passing null to stripos

---

src/nusoap.php

Fix for PHP Warning: Array to string conversion in nusoap.php on line 6069

fix - array to string conversion warning

---

src/nusoap.php

This pull request includes a change to the `parseRequest` function in the `src/nusoap.php` file. The change enhances error handling by checking for the presence of an output name in the WSDL operation data and setting an error if it is not found.

Fix undefined output on WSDL getOperationData

---

src/nusoap.php

When running from CLI (eg for tests), ['SERVER_NAME'] is not set. Check its presence to avoid missing array key

check if ['SERVER_NAME'] is set

---

src/nusoap.php

RuntimeException: Function xml_set_object() is deprecated since 8.4, provide a proper method callable to xml_set_*_handler() functions on line 6808 in file vendor/econea/nusoap/src/nusoap.php

fix deprecation warning on PHP 8.4 with xml_set_object()

---

src/nusoap.php

Reverts https://github.com/contributte/nusoap/commit/be63630028ac0405caf16a03de837a1f1e4a78eb
`$opData['output']['name']` is undefined, which causes the function to return too early. On top of that, `responseTagName` was no longer being set.
Comment on original issue: https://github.com/contributte/nusoap/issues/123#issuecomment-2665318138

revert commit be63630

---

src/nusoap.php

The `if ($message = $opData['output']['message'])` doesn't resolve the issue with the warning: 
> Undefined array key "output".
The fix should resolve the problem.
P.S.:
It is not a good practice to set values in an "if" condition.

fix: Handle warning for undefined output message
